steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ejson2env', 'ejson2env']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/external-dns', 'external-dns']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/minecraft', 'minecraft']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/pack', 'pack']
  waitFor: ['-']
images:
- gcr.io/$PROJECT_ID/ejson2env
- gcr.io/$PROJECT_ID/external-dns
- gcr.io/$PROJECT_ID/minecraft
- gcr.io/$PROJECT_ID/pack
