name: docker-push
on:
  push:
    branches: main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push cortex
        uses: docker/build-push-action@v2
        id: cortex
        with:
          push: true
          tags: jonpulsifer/cortex:latest
          context: cortex
      - name: Build and push thehive
        uses: docker/build-push-action@v2
        id: thehive
        with:
          push: true
          tags: jonpulsifer/thehive:latest
          context: thehive
